# Generated by Django 3.2 on 2022-05-02 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personage',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('pronoun', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonageStunts',
            fields=[
                ('personage', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='personages.personage')),
                ('stunts', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonageParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=64)),
                ('personage', models.ManyToManyField(to='personages.Personage')),
            ],
        ),
        migrations.CreateModel(
            name='PersonageAspectsSet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value1', models.CharField(max_length=256)),
                ('value2', models.CharField(max_length=256)),
                ('value3', models.CharField(max_length=256)),
                ('value4', models.CharField(max_length=256)),
                ('value5', models.CharField(blank=True, max_length=256)),
                ('personage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personages.personage')),
            ],
        ),
    ]
