# Generated by Django 3.2 on 2022-05-03 11:30

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('personages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personagestunts',
            name='personage',
        ),
        migrations.RenameField(
            model_name='personage',
            old_name='description',
            new_name='pers_description',
        ),
        migrations.RenameField(
            model_name='personage',
            old_name='name',
            new_name='pers_name',
        ),
        migrations.RenameField(
            model_name='personage',
            old_name='pronoun',
            new_name='pers_pronoun',
        ),
        migrations.AddField(
            model_name='personage',
            name='approach1_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach1_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach2_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach2_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach3_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach3_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach4_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach4_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach5_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach5_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach6_name',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='approach6_value',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personage',
            name='aspect1',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='aspect2',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='aspect3',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='aspect4',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='aspect5',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='consequences_mild',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='consequences_moderate',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='consequences_severe',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='personage',
            name='extras',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personage',
            name='fate_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personage',
            name='refresh',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='personage',
            name='stress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AddField(
            model_name='personage',
            name='stunts',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='personage',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PersonageAspectsSet',
        ),
        migrations.DeleteModel(
            name='PersonageStunts',
        ),
    ]
