# Generated by Django 3.2 on 2022-04-28 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonageAspectsSet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('value1', models.CharField(max_length=256)),
                ('value2', models.CharField(max_length=256)),
                ('value3', models.CharField(max_length=256)),
                ('value4', models.CharField(max_length=256)),
                ('value5', models.CharField(max_length=256)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personages.personage')),
            ],
        ),
    ]
