# Generated by Django 3.2 on 2022-04-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personages', '0003_personagestunts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personageaspectsset',
            old_name='user_id',
            new_name='personage',
        ),
    ]
