# Generated by Django 3.2 on 2022-04-30 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personages', '0005_alter_personageaspectsset_value5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personageaspectsset',
            name='value5',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
