# Generated by Django 3.2 on 2022-04-30 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personages', '0006_alter_personageaspectsset_value5'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonageParty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party', models.CharField(max_length=64)),
                ('personage', models.ManyToManyField(to='personages.Personage')),
            ],
        ),
    ]
